#include "adc_dma_bsp.h"
#include "stm32g4xx_hal.h"
#include "motor_backend.h"

// ─── ADC / current sensing (TO FILL IN) ──────────────────────────────────────
//
// The STM32G474 has 5 ADCs (ADC1–ADC5). Recommended setup for 8 shunts:
//   ADC1  channels 1–5  → MOTOR_THUMB … MOTOR_LITTLE   (PA0–PA4 or similar)
//   ADC2  channels 1–3  → MOTOR_WRIST_X … MOTOR_PALM
//
// Steps in STM32CubeIDE:
//   1. Open .ioc → Analog → ADC1 → enable scan mode, DMA continuous.
//   2. Add DMA1 Channel 1 → ADC1 in circular mode, half-word, no increment src.
//   3. Enable ADC1 global interrupt (for DMA half/full complete).
//   4. Repeat for ADC2 if needed.
//   5. Set sampling time ≥ 12.5 cycles to allow the RC filter to settle.
//   6. Update SHUNT_OHMS to match the PCB value.
//   7. In HAL_ADC_ConvCpltCallback: convert raw counts to mN and call
//      MotorBackend_OnFeedback() for each motor.
// ─────────────────────────────────────────────────────────────────────────────

#define SHUNT_OHMS     0.01f   // TODO: update to actual shunt resistance
#define ADC_VREF_MV    3300U
#define ADC_FULL_SCALE 4095U   // 12-bit

// TODO: declare hadc1 once generated by CubeMX.
// extern ADC_HandleTypeDef hadc1;

static volatile uint16_t s_adc_raw[MOTOR_COUNT];

void ADC_DMA_BSP_Init(void)
{
    // TODO: start ADC in DMA mode.
    //   HAL_ADC_Start_DMA(&hadc1, (uint32_t *)s_adc_raw, MOTOR_COUNT);
}

uint16_t ADC_DMA_BSP_GetRaw(motor_id_t id)
{
    if ((uint32_t)id >= MOTOR_COUNT) return 0U;
    return s_adc_raw[id];
}

float ADC_DMA_BSP_GetCurrentA(motor_id_t id)
{
    float voltage_v = ((float)ADC_DMA_BSP_GetRaw(id) / (float)ADC_FULL_SCALE)
                      * ((float)ADC_VREF_MV / 1000.0f);
    return voltage_v / SHUNT_OHMS;
}

// TODO: add this callback (override the HAL __weak version) once DMA is active:
//
// void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
// {
//     if (hadc != &hadc1) return;
//     for (int i = 0; i < MOTOR_COUNT; i++)
//     {
//         motor_feedback_t fb = {0};
//         fb.id       = (motor_id_t)i;
//         fb.force_mN = (uint16_t)(ADC_DMA_BSP_GetCurrentA((motor_id_t)i) * 1000.0f);
//         MotorBackend_OnFeedback(&fb);
//     }
// }
