#include "hrtim_bsp.h"
#include "stm32g4xx_hal.h"

// ─── HRTIM pin assignment (TO FILL IN) ───────────────────────────────────────
//
// STM32G474 HRTIM has 6 timer units (A–F), each with 2 outputs (x1/x2).
// Map one PWM output per motor driver IC.
//
// Suggested mapping (update once schematic is confirmed):
//   MOTOR_THUMB   (0) → HRTIM Timer A  output TA1
//   MOTOR_INDEX   (1) → HRTIM Timer A  output TA2
//   MOTOR_MIDDLE  (2) → HRTIM Timer B  output TB1
//   MOTOR_RING    (3) → HRTIM Timer B  output TB2
//   MOTOR_LITTLE  (4) → HRTIM Timer C  output TC1
//   MOTOR_WRIST_X (5) → HRTIM Timer C  output TC2
//   MOTOR_WRIST_Y (6) → HRTIM Timer D  output TD1
//   MOTOR_PALM    (7) → HRTIM Timer D  output TD2
//
// Carrier frequency: configure master period so  f_PWM = f_HRTIM / PERIOD.
// At 170 MHz and prescaler /1: PERIOD = 1700 → f_PWM = 100 kHz.
//
// Steps in STM32CubeIDE:
//   1. Open .ioc → Timers → HRTIM1 → enable Timer Units A–D.
//   2. Set each unit's period register and output polarity.
//   3. Map the alternate-function pins for TA1, TA2, TB1 … TD2.
//   4. Regenerate code → MX_HRTIM1_Init() appears in main.c.
//   5. Implement HRTIM_BSP_SetDuty() using the period value set in step 2.
// ─────────────────────────────────────────────────────────────────────────────

// TODO: declare once MX_HRTIM1_Init() is generated by CubeMX.
// extern HRTIM_HandleTypeDef hhrtim1;

// TODO: fill this table once the mapping above is confirmed.
// static const uint32_t k_hrtim_unit[MOTOR_COUNT] = {
//     HRTIM_TIMERINDEX_TIMER_A, HRTIM_TIMERINDEX_TIMER_A,
//     HRTIM_TIMERINDEX_TIMER_B, HRTIM_TIMERINDEX_TIMER_B,
//     HRTIM_TIMERINDEX_TIMER_C, HRTIM_TIMERINDEX_TIMER_C,
//     HRTIM_TIMERINDEX_TIMER_D, HRTIM_TIMERINDEX_TIMER_D,
// };
// static const uint32_t k_hrtim_out[MOTOR_COUNT] = {
//     HRTIM_OUTPUT_TA1, HRTIM_OUTPUT_TA2,
//     HRTIM_OUTPUT_TB1, HRTIM_OUTPUT_TB2,
//     HRTIM_OUTPUT_TC1, HRTIM_OUTPUT_TC2,
//     HRTIM_OUTPUT_TD1, HRTIM_OUTPUT_TD2,
// };
// #define HRTIM_PERIOD 1700U  /* gives 100 kHz at 170 MHz */

void HRTIM_BSP_Init(void)
{
    // TODO: MX_HRTIM1_Init() is called by CubeMX-generated main.c.
    //       Here, start the waveform outputs for each unit:
    //   HAL_HRTIM_WaveformOutputStart(&hhrtim1,
    //       HRTIM_OUTPUT_TA1 | HRTIM_OUTPUT_TA2 |
    //       HRTIM_OUTPUT_TB1 | HRTIM_OUTPUT_TB2 |
    //       HRTIM_OUTPUT_TC1 | HRTIM_OUTPUT_TC2 |
    //       HRTIM_OUTPUT_TD1 | HRTIM_OUTPUT_TD2);
    //   HAL_HRTIM_WaveformCountStart(&hhrtim1,
    //       HRTIM_TIMERID_TIMER_A | HRTIM_TIMERID_TIMER_B |
    //       HRTIM_TIMERID_TIMER_C | HRTIM_TIMERID_TIMER_D);
}

void HRTIM_BSP_SetDuty(motor_id_t id, float duty_0_to_1)
{
    // TODO: write the compare register for the motor's HRTIM output.
    //   if ((uint32_t)id >= MOTOR_COUNT) return;
    //   if (duty_0_to_1 < 0.0f) duty_0_to_1 = 0.0f;
    //   if (duty_0_to_1 > 1.0f) duty_0_to_1 = 1.0f;
    //   uint32_t cmp = (uint32_t)(duty_0_to_1 * (float)HRTIM_PERIOD);
    //   hhrtim1.Instance->sTimerxRegs[k_hrtim_unit[id]].CMP1xR = cmp;
    (void)id;
    (void)duty_0_to_1;
}

void HRTIM_BSP_SetAllDuty(float duty_0_to_1)
{
    for (int i = 0; i < MOTOR_COUNT; i++)
    {
        HRTIM_BSP_SetDuty((motor_id_t)i, duty_0_to_1);
    }
}
