#include "encoder_bsp.h"
#include "stm32g4xx_hal.h"

// ─── Encoder pin/timer assignment (TO FILL IN) ───────────────────────────────
//
// STM32G474 timers that support encoder mode (TIM_ENCODERMODE_TI12):
//   TIM1, TIM2, TIM3, TIM4, TIM5, TIM8
//
// Suggested mapping (update once schematic is confirmed):
//   MOTOR_THUMB   (0) → TIM1  (PA8 CH1 / PA9 CH2)
//   MOTOR_INDEX   (1) → TIM2  (PA0 CH1 / PA1 CH2)
//   MOTOR_MIDDLE  (2) → TIM3  (PA6 CH1 / PA7 CH2)
//   MOTOR_RING    (3) → TIM4  (PB6 CH1 / PB7 CH2)
//   MOTOR_LITTLE  (4) → TIM8  (PC6 CH1 / PC7 CH2)
//   MOTOR_WRIST_X (5) → TIM5  (PA0 CH1 / PA1 CH2) — resolves conflict with TIM2
//   MOTOR_WRIST_Y (6) → TIM15 (PA2 CH1 / PA3 CH2)
//   MOTOR_PALM    (7) → external counter or SPI encoder IC if no timer remains
//
// Steps in STM32CubeIDE:
//   1. Open .ioc → Timers → TIMx → Combined Channels: Encoder Mode.
//   2. Set prescaler so the counter does not overflow between reads (use 32-bit TIM2/5).
//   3. Regenerate → htimX handles appear; declare them extern here.
//   4. Set ENCODER_CPR to counts-per-revolution × gear ratio.
//   5. Implement Encoder_BSP_GetPosition() by reading __HAL_TIM_GetCounter().
// ─────────────────────────────────────────────────────────────────────────────

#define ENCODER_CPR  1024U   // TODO: update to actual CPR × gear ratio
#define CPR_TO_RAD   (6.28318530f / (float)(ENCODER_CPR))
#define VELOCITY_DT  0.01f   // expected call period in seconds (10 ms ControlTask)

// TODO: declare timer handles once generated by CubeMX.
// extern TIM_HandleTypeDef htim1, htim2, htim3, htim4, htim8;

static int32_t s_prev_count[MOTOR_COUNT];
static float   s_velocity[MOTOR_COUNT];

void Encoder_BSP_Init(void)
{
    // TODO: start all encoder timers.
    //   HAL_TIM_Encoder_Start(&htim1, TIM_CHANNEL_ALL);
    //   HAL_TIM_Encoder_Start(&htim2, TIM_CHANNEL_ALL);
    //   ... etc ...
}

float Encoder_BSP_GetPosition(motor_id_t id)
{
    // TODO: read the counter for this motor's timer and convert to radians.
    //   Example for TIM1 (motor 0):
    //   int32_t count = (int32_t)__HAL_TIM_GetCounter(&htim1);
    //   int32_t delta = count - s_prev_count[id];
    //   s_velocity[id] = (float)delta * CPR_TO_RAD / VELOCITY_DT;
    //   s_prev_count[id] = count;
    //   return (float)count * CPR_TO_RAD;
    (void)id;
    return 0.0f;
}

float Encoder_BSP_GetVelocity(motor_id_t id)
{
    // Updated as a side-effect of GetPosition(). Call GetPosition() first.
    if ((uint32_t)id >= MOTOR_COUNT) return 0.0f;
    return s_velocity[id];
}
