# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol_messages.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protocol_messages.proto\"J\n\rDeviceMessage\x12\x17\n\x05hello\x18\x01 \x01(\x0b\x32\x06.HelloH\x00\x12\x15\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x05.DataH\x00\x42\t\n\x07message\"F\n\x05Hello\x12\x11\n\tdevice_id\x18\x01 \x01(\r\x12\x11\n\tproto_ver\x18\x02 \x01(\r\x12\x17\n\x0fsupported_modes\x18\x03 \x01(\r\"=\n\x04\x44\x61ta\x12*\n\x0binstruction\x18\x01 \x01(\x0b\x32\x13.ClassificationDataH\x00\x42\t\n\x07message\"\x9c\x01\n\x12\x43lassificationData\x12*\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x1a.ClassificationData.Action\"Z\n\x06\x41\x63tion\x12\r\n\tOPEN_HAND\x10\x00\x12\x0e\n\nCLOSE_HAND\x10\x01\x12\t\n\x05PINCH\x10\x02\x12\x12\n\x0eROTATE_WRIST_R\x10\x03\x12\x12\n\x0eROTATE_WRIST_L\x10\x04\"R\n\x11ProsthesisMessage\x12\x19\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x07.ConfigH\x00\x12\x17\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x06.ErrorH\x00\x42\t\n\x07message\"<\n\x06\x43onfig\x12\x15\n\rselected_mode\x18\x01 \x01(\r\x12\x1b\n\x06params\x18\x02 \x01(\x0b\x32\x0b.ModeParams\"\x7f\n\nModeParams\x12/\n\x0e\x63lassification\x18\x01 \x01(\x0b\x32\x15.ClassificationParamsH\x00\x12/\n\nregression\x18\x02 \x01(\x0b\x32\x19.LogisticRegressionParamsH\x00\x42\x0f\n\rmode_specific\"m\n\x14\x43lassificationParams\x12\x14\n\x0c\x64\x61ta_rate_hz\x18\x01 \x01(\r\x12\x19\n\x11\x61llowed_movements\x18\x02 \x03(\r\x12\x16\n\tthreshold\x18\x03 \x01(\x02H\x00\x88\x01\x01\x42\x0c\n\n_threshold\"0\n\x18LogisticRegressionParams\x12\x14\n\x0c\x64\x61ta_rate_hz\x18\x01 \x01(\r\"\x17\n\x05\x45rror\x12\x0e\n\x06reason\x18\x01 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICEMESSAGE']._serialized_start=27
  _globals['_DEVICEMESSAGE']._serialized_end=101
  _globals['_HELLO']._serialized_start=103
  _globals['_HELLO']._serialized_end=173
  _globals['_DATA']._serialized_start=175
  _globals['_DATA']._serialized_end=236
  _globals['_CLASSIFICATIONDATA']._serialized_start=239
  _globals['_CLASSIFICATIONDATA']._serialized_end=395
  _globals['_CLASSIFICATIONDATA_ACTION']._serialized_start=305
  _globals['_CLASSIFICATIONDATA_ACTION']._serialized_end=395
  _globals['_PROSTHESISMESSAGE']._serialized_start=397
  _globals['_PROSTHESISMESSAGE']._serialized_end=479
  _globals['_CONFIG']._serialized_start=481
  _globals['_CONFIG']._serialized_end=541
  _globals['_MODEPARAMS']._serialized_start=543
  _globals['_MODEPARAMS']._serialized_end=670
  _globals['_CLASSIFICATIONPARAMS']._serialized_start=672
  _globals['_CLASSIFICATIONPARAMS']._serialized_end=781
  _globals['_LOGISTICREGRESSIONPARAMS']._serialized_start=783
  _globals['_LOGISTICREGRESSIONPARAMS']._serialized_end=831
  _globals['_ERROR']._serialized_start=833
  _globals['_ERROR']._serialized_end=856
# @@protoc_insertion_point(module_scope)
